/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    highlights: Highlight;
    quotes: Quote;
    events: Event;
    'daily-impulses': DailyImpulse;
    documents: Document;
    'program-topic-categories': ProgramTopicCategory;
    'wahlomat-elections': WahlomatElection;
    'blog-categories': BlogCategory;
    'blog-posts': BlogPost;
    'weekly-essays': WeeklyEssay;
    'beirat-members': BeiratMember;
    'prompt-templates': PromptTemplate;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    highlights: HighlightsSelect<false> | HighlightsSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'daily-impulses': DailyImpulsesSelect<false> | DailyImpulsesSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'program-topic-categories': ProgramTopicCategoriesSelect<false> | ProgramTopicCategoriesSelect<true>;
    'wahlomat-elections': WahlomatElectionsSelect<false> | WahlomatElectionsSelect<true>;
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'weekly-essays': WeeklyEssaysSelect<false> | WeeklyEssaysSelect<true>;
    'beirat-members': BeiratMembersSelect<false> | BeiratMembersSelect<true>;
    'prompt-templates': PromptTemplatesSelect<false> | PromptTemplatesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | 'de' | 'de'[];
  globals: {
    program: Program;
    beirat: Beirat;
    freiheitsbewegung: Freiheitsbewegung;
  };
  globalsSelect: {
    program: ProgramSelect<false> | ProgramSelect<true>;
    beirat: BeiratSelect<false> | BeiratSelect<true>;
    freiheitsbewegung: FreiheitsbewegungSelect<false> | FreiheitsbewegungSelect<true>;
  };
  locale: 'de';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Aktuelle Meldungen und Kampagnen – z. B. Afuera Fest. Maximal ein bis zwei gleichzeitig aktiv halten.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "highlights".
 */
export interface Highlight {
  id: string;
  /**
   * Große Überschrift im Highlight-Bereich.
   */
  title: string;
  /**
   * Kurzname für interne Zuordnung (wird automatisch aus dem Titel erzeugt).
   */
  slug?: string | null;
  /**
   * 1–3 Sätze unter der Überschrift. Plain Text, kein HTML nötig.
   */
  shortText: string;
  /**
   * Wird als Info-Zeile angezeigt (z. B. Fest-Datum).
   */
  date?: string | null;
  /**
   * Optional: Highlight wird nach diesem Datum automatisch ausgeblendet.
   */
  activeUntil?: string | null;
  /**
   * Querformat empfohlen (z. B. 1200 × 800 px).
   */
  image?: (string | null) | Media;
  /**
   * Ziel des Buttons – intern (/events) oder extern (https://…).
   */
  link: string;
  /**
   * Nur aktive Highlights erscheinen unter „Aktuell bei DIE LIBERTÄREN“.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Zitate rotieren automatisch auf der Startseite. Mindestens ein veröffentlichtes Zitat empfohlen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: string;
  /**
   * Der Zitat-Text in Anführungszeichen auf der Startseite.
   */
  quoteText: string;
  authorName: string;
  /**
   * z. B. „Bundesvorsitzender DIE LIBERTÄREN"
   */
  authorTitle?: string | null;
  /**
   * Optional: Porträt neben dem Zitat.
   */
  authorImage?: (string | null) | Media;
  /**
   * z. B. Rede, Interview, Twitter/X, Buchtitel.
   */
  source?: string | null;
  /**
   * Nur veröffentlichte Zitate erscheinen in der Rotation.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Termine, Stammtische und Feste – erscheinen auf der Startseite und unter /events.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  title: string;
  startDate: string;
  /**
   * Für mehrtägige Events. Leer lassen bei eintägigen Terminen.
   */
  endDate?: string | null;
  /**
   * Stadt oder Venue, z. B. „Hamburg" oder „Camping Strandbad Gerlebogk".
   */
  location: string;
  category: 'stammtisch' | 'fest' | 'parteitag' | 'veranstaltung' | 'workshop' | 'sonstiges';
  /**
   * Kurze Info zum Event – optional, wird auf der Events-Seite angezeigt.
   */
  description?: string | null;
  image?: (string | null) | Media;
  /**
   * Optional: Anmeldung oder externe Infoseite. Standard: /events
   */
  link?: string | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kurze News mit libertärer Einordnung. Die 3 neuesten veröffentlichten Impulse erscheinen auf der Startseite.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "daily-impulses".
 */
export interface DailyImpulse {
  id: string;
  title: string;
  /**
   * Kurze Zusammenfassung der Meldung (2–4 Sätze).
   */
  shortText: string;
  /**
   * Warum ist das für Libertäre relevant? Freiheitliche Perspektive in 1–3 Sätzen.
   */
  libertarianPerspective: string;
  date: string;
  /**
   * Link zur Originalquelle oder zum Blog-Artikel.
   */
  sourceLink?: string | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: string;
  title: string;
  slug?: string | null;
  category: 'thesenpapier' | 'satzung' | 'positionspapier' | 'sonstiges';
  description?: string | null;
  file: string | Media;
  publishedAt?: string | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kategorien mit konkreten Themen und Maßnahmen für das Thesenpapier.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program-topic-categories".
 */
export interface ProgramTopicCategory {
  id: string;
  category: string;
  pillar: 'individuell' | 'vertraglich' | 'gesellschaftlich';
  /**
   * Niedrigere Zahlen erscheinen zuerst.
   */
  sortOrder?: number | null;
  items?:
    | {
        topic: string;
        massnahme: string;
        id?: string | null;
      }[]
    | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Wahl-O-Mat-Thesen pro Wahl (z. B. Sachsen-Anhalt 2026). Eine Wahl als Standard markieren.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wahlomat-elections".
 */
export interface WahlomatElection {
  id: string;
  title: string;
  /**
   * URL-Kennung, z. B. sachsen-anhalt-2026
   */
  slug?: string | null;
  subtitle?: string | null;
  region: string;
  year: number;
  source?: string | null;
  /**
   * Wird auf der Wahl-O-Mat-Seite vorausgewählt.
   */
  isDefault?: boolean | null;
  thesen?:
    | {
        theseNumber: number;
        theseText: string;
        position: 'Ja' | 'Nein' | 'Neutral';
        begruendung: string;
        category: string;
        id?: string | null;
      }[]
    | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: string;
  name: string;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Vollständige Blog-Artikel mit Rich Text.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: string;
  title: string;
  slug?: string | null;
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  date: string;
  author?: string | null;
  featuredImage?: (string | null) | Media;
  category: string | BlogCategory;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Libertärer Aufsatz der Woche – wird nach Kalenderwoche auf Blog und Startseite angezeigt.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weekly-essays".
 */
export interface WeeklyEssay {
  id: string;
  week: number;
  title: string;
  author?: string | null;
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Mitglieder des Beirats – Foto, Rolle und Kurzbiografie.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "beirat-members".
 */
export interface BeiratMember {
  id: string;
  name: string;
  role: string;
  bio: string;
  /**
   * Empfohlen: quadratisches Porträt. Alternativ externe Bild-URL unten.
   */
  photo?: (string | null) | Media;
  /**
   * Externe URL, wenn kein Upload in Medien vorhanden ist.
   */
  imageUrl?: string | null;
  deceased?: boolean | null;
  /**
   * z. B. „24. Mai 2026"
   */
  deceasedDate?: string | null;
  /**
   * Kleinere Zahl = weiter oben.
   */
  sortOrder?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * System-Prompts für Grok-Skripte (z. B. generate:daily). Slug nicht ändern, sobald verknüpft.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prompt-templates".
 */
export interface PromptTemplate {
  id: string;
  name: string;
  /**
   * Technischer Schlüssel. Nur ein Eintrag pro Schlüssel. Nicht ändern, wenn das Skript bereits darauf verweist.
   */
  slug: 'daily-impulses-system';
  /**
   * Anweisungen an Grok (Rolle, Ton, Sprache, JSON-Ausgabe). Wird von generate:daily als system-Nachricht verwendet.
   */
  systemPrompt: string;
  /**
   * Optional: Hinweise für Redakteure, nicht an Grok gesendet.
   */
  description?: string | null;
  /**
   * Inaktive Vorlagen werden ignoriert – das Skript nutzt dann den Standard-Prompt aus dem Code.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'highlights';
        value: string | Highlight;
      } | null)
    | ({
        relationTo: 'quotes';
        value: string | Quote;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'daily-impulses';
        value: string | DailyImpulse;
      } | null)
    | ({
        relationTo: 'documents';
        value: string | Document;
      } | null)
    | ({
        relationTo: 'program-topic-categories';
        value: string | ProgramTopicCategory;
      } | null)
    | ({
        relationTo: 'wahlomat-elections';
        value: string | WahlomatElection;
      } | null)
    | ({
        relationTo: 'blog-categories';
        value: string | BlogCategory;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: string | BlogPost;
      } | null)
    | ({
        relationTo: 'weekly-essays';
        value: string | WeeklyEssay;
      } | null)
    | ({
        relationTo: 'beirat-members';
        value: string | BeiratMember;
      } | null)
    | ({
        relationTo: 'prompt-templates';
        value: string | PromptTemplate;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "highlights_select".
 */
export interface HighlightsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortText?: T;
  date?: T;
  activeUntil?: T;
  image?: T;
  link?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  quoteText?: T;
  authorName?: T;
  authorTitle?: T;
  authorImage?: T;
  source?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  startDate?: T;
  endDate?: T;
  location?: T;
  category?: T;
  description?: T;
  image?: T;
  link?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "daily-impulses_select".
 */
export interface DailyImpulsesSelect<T extends boolean = true> {
  title?: T;
  shortText?: T;
  libertarianPerspective?: T;
  date?: T;
  sourceLink?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  description?: T;
  file?: T;
  publishedAt?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program-topic-categories_select".
 */
export interface ProgramTopicCategoriesSelect<T extends boolean = true> {
  category?: T;
  pillar?: T;
  sortOrder?: T;
  items?:
    | T
    | {
        topic?: T;
        massnahme?: T;
        id?: T;
      };
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wahlomat-elections_select".
 */
export interface WahlomatElectionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  region?: T;
  year?: T;
  source?: T;
  isDefault?: T;
  thesen?:
    | T
    | {
        theseNumber?: T;
        theseText?: T;
        position?: T;
        begruendung?: T;
        category?: T;
        id?: T;
      };
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  date?: T;
  author?: T;
  featuredImage?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weekly-essays_select".
 */
export interface WeeklyEssaysSelect<T extends boolean = true> {
  week?: T;
  title?: T;
  author?: T;
  excerpt?: T;
  content?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "beirat-members_select".
 */
export interface BeiratMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  photo?: T;
  imageUrl?: T;
  deceased?: T;
  deceasedDate?: T;
  sortOrder?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prompt-templates_select".
 */
export interface PromptTemplatesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  systemPrompt?: T;
  description?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Titel, Leitbild, Grundthese und erste Maßnahmen des Thesenpapiers.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program".
 */
export interface Program {
  id: string;
  title: string;
  subtitle?: string | null;
  /**
   * Optional: PDF zum Download auf der Programm-Seite.
   */
  pdfFile?: (string | null) | Media;
  leitbild: {
    vision: {
      title: string;
      headline: string;
      text: string;
    };
    mission: {
      title: string;
      headline: string;
      text: string;
    };
    values: {
      title: string;
      headline: string;
      text: string;
    };
  };
  grundthese: {
    title?: string | null;
    text: string;
    pillars?:
      | {
          id: 'individuell' | 'vertraglich' | 'gesellschaftlich';
          title: string;
          subtitle: string;
          description: string;
        }[]
      | null;
  };
  ersteMassnahmen?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Einleitung, Aufgaben, Nachruf und Kontakt-Hinweis für die Beirat-Seite.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "beirat".
 */
export interface Beirat {
  id: string;
  pageTitle: string;
  pageSubtitle?: string | null;
  intro: string;
  tasksSectionTitle?: string | null;
  tasks?:
    | {
        icon: 'book-open' | 'line-chart' | 'megaphone' | 'search' | 'user-search' | 'users';
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  membersSectionTitle?: string | null;
  membersSectionSubtitle?: string | null;
  nachruf: {
    enabled?: boolean | null;
    badgeLabel?: string | null;
    title?: string | null;
    subtitle?: string | null;
    body: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  contactHint?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Geschichte, Österreichische Schule und Meilensteine.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "freiheitsbewegung".
 */
export interface Freiheitsbewegung {
  id: string;
  pageTitle: string;
  pageSubtitle?: string | null;
  introParagraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  austrianSchool: {
    title?: string | null;
    subtitle?: string | null;
    cardLeft: {
      title: string;
      paragraphs?:
        | {
            text: string;
            id?: string | null;
          }[]
        | null;
    };
    cardRight: {
      title: string;
      paragraphs?:
        | {
            text: string;
            id?: string | null;
          }[]
        | null;
    };
  };
  figuresSectionTitle?: string | null;
  figures?:
    | {
        name: string;
        years: string;
        role: string;
        photo?: (string | null) | Media;
        imageUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  history?: {
    title?: string | null;
    subtitle?: string | null;
    paragraphs?:
      | {
          icon?: ('book-open' | 'globe') | null;
          text: string;
          id?: string | null;
        }[]
      | null;
    milestonesTitle?: string | null;
    milestones?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program_select".
 */
export interface ProgramSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  pdfFile?: T;
  leitbild?:
    | T
    | {
        vision?:
          | T
          | {
              title?: T;
              headline?: T;
              text?: T;
            };
        mission?:
          | T
          | {
              title?: T;
              headline?: T;
              text?: T;
            };
        values?:
          | T
          | {
              title?: T;
              headline?: T;
              text?: T;
            };
      };
  grundthese?:
    | T
    | {
        title?: T;
        text?: T;
        pillars?:
          | T
          | {
              id?: T;
              title?: T;
              subtitle?: T;
              description?: T;
            };
      };
  ersteMassnahmen?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "beirat_select".
 */
export interface BeiratSelect<T extends boolean = true> {
  pageTitle?: T;
  pageSubtitle?: T;
  intro?: T;
  tasksSectionTitle?: T;
  tasks?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  membersSectionTitle?: T;
  membersSectionSubtitle?: T;
  nachruf?:
    | T
    | {
        enabled?: T;
        badgeLabel?: T;
        title?: T;
        subtitle?: T;
        body?: T;
      };
  contactHint?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "freiheitsbewegung_select".
 */
export interface FreiheitsbewegungSelect<T extends boolean = true> {
  pageTitle?: T;
  pageSubtitle?: T;
  introParagraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  austrianSchool?:
    | T
    | {
        title?: T;
        subtitle?: T;
        cardLeft?:
          | T
          | {
              title?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
            };
        cardRight?:
          | T
          | {
              title?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
            };
      };
  figuresSectionTitle?: T;
  figures?:
    | T
    | {
        name?: T;
        years?: T;
        role?: T;
        photo?: T;
        imageUrl?: T;
        id?: T;
      };
  history?:
    | T
    | {
        title?: T;
        subtitle?: T;
        paragraphs?:
          | T
          | {
              icon?: T;
              text?: T;
              id?: T;
            };
        milestonesTitle?: T;
        milestones?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}